-- Snapshot of the schema as it existed before household support was added.
-- On a fresh database this runs for real. Against the existing production
-- database (which already has this exact shape from Hibernate's old
-- ddl-auto: update behavior), Flyway's baseline-on-migrate skips this file
-- and starts real migrations at V2.

CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    icon VARCHAR(255)
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    instructions TEXT,
    servings INTEGER,
    preparation_time_minutes INTEGER,
    cooking_time_minutes INTEGER,
    difficulty VARCHAR(255),
    cuisine VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL REFERENCES recipes(id),
    ingredient_name VARCHAR(255) NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    unit VARCHAR(255) NOT NULL,
    optional BOOLEAN NOT NULL,
    notes VARCHAR(255)
);

CREATE TABLE inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    location_id BIGINT NOT NULL REFERENCES locations(id),
    quantity DOUBLE PRECISION NOT NULL,
    unit VARCHAR(255) NOT NULL,
    expiry_date DATE,
    added_date DATE,
    expired BOOLEAN NOT NULL,
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
