-- Adds household support and scopes existing data (users, locations,
-- inventory items, recipes) to a single household so nothing changes for
-- Sean and Natalia. New registrations get their own household afterward via
-- the application, not this migration.

CREATE TABLE households (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE household_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id BIGINT NOT NULL REFERENCES households(id),
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    invited_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP
);

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id),
    token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP
);

-- Seed one household for any pre-existing data. On a fresh install app_users
-- is empty at this point (bootstrap runs later, after Flyway), so this is a
-- no-op there and the app's own bootstrap creates its own household instead.
INSERT INTO households (name, created_at)
SELECT 'Sean & Natalia''s Household', now()
WHERE EXISTS (SELECT 1 FROM app_users);

-- app_users: email, last_name, household_id
ALTER TABLE app_users ADD COLUMN email VARCHAR(255);
ALTER TABLE app_users ADD COLUMN last_name VARCHAR(255);
ALTER TABLE app_users ADD COLUMN household_id BIGINT;

UPDATE app_users SET household_id = (SELECT id FROM households ORDER BY id LIMIT 1)
WHERE household_id IS NULL;

UPDATE app_users SET email = 'deroosean@gmail.com', last_name = 'de Roo'
WHERE username = 'sean' AND email IS NULL;

UPDATE app_users SET email = 'nacardenasni@gmail.com', last_name = 'Cardenas Nino'
WHERE username = 'natalia' AND email IS NULL;

ALTER TABLE app_users ALTER COLUMN household_id SET NOT NULL;
ALTER TABLE app_users ALTER COLUMN email SET NOT NULL;
ALTER TABLE app_users ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE app_users ADD CONSTRAINT uk_app_users_email UNIQUE (email);
ALTER TABLE app_users ADD CONSTRAINT fk_app_users_household FOREIGN KEY (household_id) REFERENCES households(id);

-- locations: household_id, and name is now unique per household instead of globally
ALTER TABLE locations ADD COLUMN household_id BIGINT;

UPDATE locations SET household_id = (SELECT id FROM households ORDER BY id LIMIT 1)
WHERE household_id IS NULL;

ALTER TABLE locations ALTER COLUMN household_id SET NOT NULL;
ALTER TABLE locations ADD CONSTRAINT fk_locations_household FOREIGN KEY (household_id) REFERENCES households(id);

DO $$
DECLARE
    old_constraint text;
BEGIN
    SELECT conname INTO old_constraint
    FROM pg_constraint
    WHERE conrelid = 'locations'::regclass
      AND contype = 'u'
      AND array_length(conkey, 1) = 1;
    IF old_constraint IS NOT NULL THEN
        EXECUTE format('ALTER TABLE locations DROP CONSTRAINT %I', old_constraint);
    END IF;
END $$;

ALTER TABLE locations ADD CONSTRAINT uk_locations_name_household UNIQUE (name, household_id);

-- inventory_items: household_id
ALTER TABLE inventory_items ADD COLUMN household_id BIGINT;

UPDATE inventory_items SET household_id = (SELECT id FROM households ORDER BY id LIMIT 1)
WHERE household_id IS NULL;

ALTER TABLE inventory_items ALTER COLUMN household_id SET NOT NULL;
ALTER TABLE inventory_items ADD CONSTRAINT fk_inventory_items_household FOREIGN KEY (household_id) REFERENCES households(id);

-- recipes: household_id
ALTER TABLE recipes ADD COLUMN household_id BIGINT;

UPDATE recipes SET household_id = (SELECT id FROM households ORDER BY id LIMIT 1)
WHERE household_id IS NULL;

ALTER TABLE recipes ALTER COLUMN household_id SET NOT NULL;
ALTER TABLE recipes ADD CONSTRAINT fk_recipes_household FOREIGN KEY (household_id) REFERENCES households(id);
